[build]
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; object-src 'none';"
    Cross-Origin-Embedder-Policy = "unsafe-none"

[[headers]]
  for = "/index.html"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
